##  Numpy
it's a library in python in data science numerical python have alot of use its also called numerical python it's a core library of python.
mostly use for mathematicially formulas and statistical analysis.


first of all you have to install in pip in terminal window 
"pip install numpy" 

then you have to import library as np

In [2]:
import numpy as np

How its loooks like?


In [3]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

numpy is similar to list like [2,3,3,4,5,6]
what is the d/f list and numpy 
numpy is mast faster then list
you can use only one type data in numpy and list you can use different type of data

what is an array?
- an array is a central data structure of the numpy library. e.h list, tuple, booleans, which contain information 
e.g take a shopper which have contain samosai pakorai another example morning assembly in school

In [4]:
a = np.array([5,5,5,5,5,5,5,5])
a

array([5, 5, 5, 5, 5, 5, 5, 5])

In [5]:
type(a)

numpy.ndarray

nd means one dimensial array

In [6]:
b = np.array(([5,5,5,5],[5,5,5,5],[5,5,5,5]))
b

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

Vector is an array with a single dimension. no difference b/w row and column like morning assimbly 
- mitrix refers to an array with two dimensions

In [7]:
len(b)

3

In [8]:
#indexing
b[1]

array([5, 5, 5, 5])

In [9]:
# 3D is higer dimentsional arrays tensor is a library commonly used
# - dimesions are called axis
c = np.array([[5,5,5,5],[5,5,5,5]])
c

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [10]:
#how to creat array?
d = np.ones(4)
d

array([1., 1., 1., 1.])

In [11]:
e = np.empty(3)
e

array([3.44900369e-307, 4.67293351e-307, 4.22786102e-307])

In [12]:
# makking array through arange
f = np.arange(5)
f

array([0, 1, 2, 3, 4])

In [13]:
#specific range
g = np.arange(5, 20)
g

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
# continue... 
h = np.arange(5, 30, 5)
h

array([ 5, 10, 15, 20, 25])

In [15]:
# linerly spaced arrays
i = np.linspace(0, 10, num=5)
i

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
# specific data type in array
j = np.ones(5, dtype=np.int8)
j

array([1, 1, 1, 1, 1], dtype=int8)

In [17]:
k = np.ones(3, dtype=np.float64)
k

array([1., 1., 1.])

In [18]:
#how to creat 2D array?
l = np.ones((3,4))
l

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
#how to creat 2D array?
m = np.ones((3,5))
m

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
#how to creat 3D array?
n = np.arange(24).reshape(2,3,4)
n

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
fname=np.array(["ijaz","ali","jin"])
fname

array(['ijaz', 'ali', 'jin'], dtype='<U4')

In [23]:
nu = np.array([3,4,5,])
nu

array([3, 4, 5])

In [24]:
fname[2]

'jin'

In [26]:
fname.size

3

In [27]:
nu.mean()

4.0

In [29]:
rang = np.arange(5)
rang

array([0, 1, 2, 3, 4])

In [30]:
#start form 5 and end 20
rang1 = np.arange(5, 20)
rang1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
# 3 is for interval
rang2 = np.arange(5, 20, 3)
rang2

array([ 5,  8, 11, 14, 17])

In [34]:
rang3 = np.linspace(5, 50, 5)
rang3
#same result of you substract

array([ 5.  , 16.25, 27.5 , 38.75, 50.  ])

In [36]:
a = np.array([10,20.7,30,40,23,643,63,723,674])
a

array([ 10. ,  20.7,  30. ,  40. ,  23. , 643. ,  63. , 723. , 674. ])

In [38]:
a.sort()
a

array([ 10. ,  20.7,  23. ,  30. ,  40. ,  63. , 643. , 674. , 723. ])

In [39]:
#explore the function after .
a.all()
a

array([ 10. ,  20.7,  23. ,  30. ,  40. ,  63. , 643. , 674. , 723. ])

In [41]:
b= np.array([24,245,647,8545,34,64])
b

array([  24,  245,  647, 8545,   34,   64])

In [47]:
#concatinate mean combiune
c= np.concatenate((a,b))
c

array([  10. ,   20.7,   23. ,   30. ,   40. ,   63. ,  643. ,  674. ,
        723. ,   24. ,  245. ,  647. , 8545. ,   34. ,   64. ])

In [49]:
c.sort()
c

array([  10. ,   20.7,   23. ,   24. ,   30. ,   34. ,   40. ,   63. ,
         64. ,  245. ,  643. ,  647. ,  674. ,  723. , 8545. ])

# 2-D arrays

In [50]:
z = np.array([[1,2,3,4],[9,8,7,6]])
z

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [51]:
x = np.array([[3,4,5,6],[2,6,7,22]])
x

array([[ 3,  4,  5,  6],
       [ 2,  6,  7, 22]])

In [52]:
np.concatenate((z,x), axis =1)

array([[ 1,  2,  3,  4,  3,  4,  5,  6],
       [ 9,  8,  7,  6,  2,  6,  7, 22]])

In [58]:
x.size


8

In [59]:
x.shape

(2, 4)